import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Formcraft</title>
      </head>
      <body>
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}
